perl sort2bed.pl -g example/test.fa -f gene -i example/test.bed -t bed2gff -o bed2gff.out 
perl sort2bed.pl -g example/test.fa -f gene -i example/test.bed -t bed2ptt -o bed2ptt.out 
perl sort2bed.pl -g example/test.fa -f gene -i example/test.bed -t bed2sort -o bed2sort.out 
perl sort2bed.pl -g example/test.fa -f gene -i example/test.bed -t bed2fa -o bed2fa.out 
perl sort2bed.pl -g example/test.fa -f gene -i example/test.gff -t gff2ptt -o gff2ptt.out 
perl sort2bed.pl -g example/test.fa -f gene -i example/test.gff -t gff2bed -o gff2bed.out 
perl sort2bed.pl -g example/test.fa -f gene -i example/test.gff -t gff2sort -o gff2sort.out 
perl sort2bed.pl -g example/test.fa -f gene -i example/test.gff -t gff2fa -o gff2fa.out 
perl sort2bed.pl -g example/test.fa -f gene -i example/test.ptt -t ptt2gff -o ptt2gff.out 
perl sort2bed.pl -g example/test.fa -f gene -i example/test.ptt -t ptt2bed -o ptt2bed.out 
perl sort2bed.pl -g example/test.fa -f gene -i example/test.ptt -t ptt2sort -o ptt2sort.out 
perl sort2bed.pl -g example/test.fa -f gene -i example/test.ptt -t ptt2fa -o ptt2fa.out 
perl sort2bed.pl -g example/test.fa -f gene -i example/test.txt -t sort2gff -o sort2gff.out 
perl sort2bed.pl -g example/test.fa -f gene -i example/test.txt -t sort2ptt -o sort2ptt.out 
perl sort2bed.pl -g example/test.fa -f gene -i example/test.txt -t sort2bed -o sort2bed.out 
perl sort2bed.pl -g example/test.fa -f gene -i example/test.txt -t sort2fa -o sort2fa.out 
